#!/usr/bin/env bash

hdmi_active=$(xrandr |grep ' connected' |grep 'HDMI' |awk '{print $1}')
if [[ ! -z "$hdmi_active" ]] 

then
    xrandr --output eDP-1 --primary --mode 2560x1440 --pos 0x1080 --rotate normal --output DP-1 --off --output DP-2 --off --output HDMI-1-0 --mode 1920x1080 --pos 0x0 --rotate normal --output DP-1-0 --off



else
    xrandr --output eDP-1 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output DP-1 --off --output DP-2 --off --output HDMI-1-0 --off --output DP-1-0 --off

fi

